### ISSUE TITLE
devise_forにまとめましょう

### ISSUE THREAD

**Issue by norotime** [KazuhiroObama/event-keeper2#3]
https://github.com/KazuhiroObama/event-keeper2/blob/0a31e89e41831e563554e5bb8719d4cb1c2fc659/config/routes.rb#L9

**Comment by PEPSINEX** [comment]
「devise_forにまとめる」とは、このような認識でよろしいですか？

**Comment by norotime** [comment]
@KazuhiroObama そんな感じですね！Deviseのページに user#showについてどう書けば良いか？などWikiに載っていませんか？（載っていなかったらすみませんw
